name: E2E

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

env:
  HUSKY: 0

jobs:
  e2e:
    name: E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/new-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/new-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Flipped around

      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/non-existent.json
          base-stats-json-path: ./__tests__/__mocks__/non-existent.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Non existent

      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: No changes

      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/new-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: "With describe-assets: 'none'"
          describe-assets: none

      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: "With describe-assets: 'changed-only'"
          describe-assets: changed-only
